### ISSUE TITLE
Feeling puzzled  about one code line in Convolutional.cpp?

### ISSUE THREAD

**Issue by dazhenseu** [henrygouk/nnet#2]
Hi~
  The Convolutional.cpp implements the convolution in frequency domain, and it seems this code line
https://github.com/henrygouk/nnet/blob/master/source/Convolutional.cpp#L183
 only add biase to the first elements of every output map image.Is it okay?
 So why not first transform the frequency output map to spatial domain and then add the same bias to each element of every output map image?

**Comment by henrygouk** [comment]
That adds the bias to the DC component of the frequency domain representation. This is equivalent to adding the bias to each element of the space domain representation.
